[dependencies]
  CJson = { path = "../CJson" ,version = "1.0.0"}
[package]
  cjc-version = "0.53.13"
  name = "cjsonExample"
  version = "1.0.0"
  output-type = "executable"

  compile-option = "-Woff unused --debug-macro"
  description = "nothing here"
  link-option = ""
  src-dir = ""
  target-dir = ""

  [package.package-configuration]
  [package.scripts]
