[dependencies]

[package]
  cjc-version = "0.53.13"
  name = "CJson"
  version = "1.0.0"
  output-type = "static"

  #compile-option = "--debug-macro" #used for debugging macro
  compile-option = "-Woff unused --debug-macro"
  description = "nothing here"
  link-option = ""
  src-dir = ""
  target-dir = ""

  [package.package-configuration]